name: Format2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  YAMLFormat1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        
      - name: Check out code
        uses: actions/checkout@v2
      - name: YAMLFormat
        run: |
         
         go mod tidy
         go run yaml.go main.go
        
