name: Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  YAMLFormat:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        
      - name: Check out code
        uses: actions/checkout@v2

      - name: Tidy Go module
        run: |
         
         go mod tidy -compat=1.17


      - name: YAMLFormat
        run: |
      
         go run main.go
        



